---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
    # channel: "eslint-2"
    # plugins: "wordpress"
    # extends: "plugin:wordpress/recommended"
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.module"
  - "**.php"
exclude_paths:
- node_modules/
